stages:
  download_data:
    cmd: python src/download_data.py
    deps:
    - src/download_data.py
    outs:
    - data/raw/iris.csv
  
  clean_data:
    cmd: python src/data_processing.py
    deps:
    - src/data_processing.py
    - data/raw/iris.csv
    outs:
    - data/processed/iris_processed.csv

  train_model:
    cmd: python src/train_model.py
    deps:
    - src/train_model.py
    - data/processed/iris_processed.csv
    outs:
    - models/logistic_regression_model.pkl
    - models/random_forest_model.pkl
    - models/features.json
    metrics:
    - models/metrics.json

